import { z } from 'zod/v4'
import type { FormSchema } from './schema'

export const contactFormSchema: FormSchema = {
    title: 'Dynamic Form',
    description:
        'A fully dynamic form demonstrating all input types, conditional fields, repeatable groups, and multi-step validation.',
    steps: [
        {
            title: 'Personal Info',
            description: 'Tell us about yourself.',
            fields: [
                {
                    name: 'fullName',
                    label: 'Full Name',
                    type: 'text',
                    placeholder: 'John Doe',
                    validation: z.string().min(1, 'Full Name is required'),
                },
                {
                    name: 'email',
                    label: 'Email',
                    type: 'email',
                    placeholder: 'john@example.com',
                    validation: z.email('Please enter a valid email address'),
                },
                {
                    name: 'password',
                    label: 'Password',
                    type: 'password',
                    placeholder: 'Min 8 characters',
                    validation: z.string().min(8, 'Password must be at least 8 characters'),
                },
                {
                    name: 'age',
                    label: 'Age',
                    type: 'number',
                    placeholder: '25',
                    validation: z.number({ error: 'Age must be a valid number' }).min(1, 'Age must be at least 1').max(150, 'Age must be at most 150').optional(),
                },
                {
                    name: 'dob',
                    label: 'Date of Birth',
                    type: 'date',
                    validation: z.string().min(1, 'Date of Birth is required'),
                },
                {
                    name: 'favoriteColor',
                    label: 'Favorite Color',
                    type: 'color',
                    defaultValue: '#6366f1',
                    validation: z.string().regex(
                        /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/,
                        'Please enter a valid hex color (e.g. #FFF or #FFFFFF)'
                    ),
                },
            ],
        },
        {
            title: 'Preferences',
            description: 'Customize your experience.',
            fields: [
                {
                    name: 'country',
                    label: 'Country',
                    type: 'select',
                    options: [
                        { label: 'United States', value: 'us' },
                        { label: 'Canada', value: 'ca' },
                        { label: 'United Kingdom', value: 'uk' },
                        { label: 'Germany', value: 'de' },
                        { label: 'Japan', value: 'jp' },
                        { label: 'Australia', value: 'au' },
                        { label: 'India', value: 'in' },
                        { label: 'Brazil', value: 'br' },
                    ],
                    validation: z.string().min(1, 'Country is required'),
                },
                {
                    name: 'language',
                    label: 'Preferred Language',
                    type: 'combobox',
                    placeholder: 'Search languages...',
                    options: [
                        { label: 'English', value: 'en' },
                        { label: 'Spanish', value: 'es' },
                        { label: 'French', value: 'fr' },
                        { label: 'German', value: 'de' },
                        { label: 'Japanese', value: 'ja' },
                        { label: 'Portuguese', value: 'pt' },
                        { label: 'Chinese', value: 'zh' },
                        { label: 'Hindi', value: 'hi' },
                        { label: 'Arabic', value: 'ar' },
                        { label: 'Korean', value: 'ko' },
                    ],
                    validation: z.string().min(1, 'Preferred Language is required'),
                },
                {
                    name: 'contactMethod',
                    label: 'Preferred Contact Method',
                    type: 'radio',
                    options: [
                        { label: 'Email', value: 'email' },
                        { label: 'Phone', value: 'phone' },
                        { label: 'Mail', value: 'mail' },
                    ],
                    validation: z.string().min(1, 'Preferred Contact Method is required'),
                },
                {
                    name: 'subscribeNewsletter',
                    label: 'Subscribe to Newsletter',
                    type: 'checkbox',
                    defaultValue: false,
                    validation: z.boolean(),
                },
                {
                    name: 'enableDarkMode',
                    label: 'Enable Dark Mode',
                    type: 'switch',
                    defaultValue: false,
                    validation: z.boolean(),
                },
                {
                    name: 'experienceLevel',
                    label: 'Experience Level',
                    type: 'slider',
                    min: 0,
                    max: 100,
                    step: 1,
                    defaultValue: 50,
                    validation: z.number().min(0).max(100),
                },
                {
                    name: 'bio',
                    label: 'Bio',
                    type: 'textarea',
                    placeholder: 'Tell us a bit about yourself...',
                    validation: z.string().max(500, 'Bio must be at most 500 characters').optional(),
                },
            ],
        },
        {
            title: 'Files & Addresses',
            description: 'Upload files and manage your addresses.',
            fields: [
                {
                    name: 'profilePicture',
                    label: 'Profile Picture',
                    type: 'file',
                    accept: 'image/*',
                    validation: z.union([z.instanceof(File), z.array(z.instanceof(File)), z.string()]).optional(),
                },
                {
                    name: 'documents',
                    label: 'Documents',
                    type: 'file',
                    accept: '.pdf,.doc,.docx',
                    multiple: true,
                    validation: z.union([z.instanceof(File), z.array(z.instanceof(File)), z.string()]).optional(),
                },
                {
                    kind: 'repeatable',
                    name: 'addresses',
                    label: 'Addresses',
                    min: 1,
                    max: 5,
                    fields: [
                        {
                            name: 'street',
                            label: 'Street',
                            type: 'text',
                            placeholder: '123 Main St',
                            validation: z.string().min(1, 'Street is required'),
                        },
                        {
                            name: 'city',
                            label: 'City',
                            type: 'text',
                            placeholder: 'New York',
                            validation: z.string().min(1, 'City is required'),
                        },
                        {
                            name: 'state',
                            label: 'State',
                            type: 'select',
                            options: [
                                { label: 'California', value: 'ca' },
                                { label: 'New York', value: 'ny' },
                                { label: 'Texas', value: 'tx' },
                                { label: 'Florida', value: 'fl' },
                                { label: 'Illinois', value: 'il' },
                            ],
                            validation: z.string(),
                        },
                        {
                            name: 'zip',
                            label: 'ZIP Code',
                            type: 'text',
                            placeholder: '10001',
                            validation: z.string(),
                        },
                    ],
                },
                {
                    name: 'mailingStreet',
                    label: 'Mailing Street',
                    type: 'text',
                    placeholder: '456 Mail Ave',
                    conditional: {
                        field: 'contactMethod',
                        operator: 'equals',
                        value: 'mail',
                    },
                    validation: z.string().optional(),
                },
                {
                    name: 'mailingCity',
                    label: 'Mailing City',
                    type: 'text',
                    placeholder: 'Los Angeles',
                    conditional: {
                        field: 'contactMethod',
                        operator: 'equals',
                        value: 'mail',
                    },
                    validation: z.string().optional(),
                },
                {
                    name: 'mailingZip',
                    label: 'Mailing ZIP',
                    type: 'text',
                    placeholder: '90001',
                    conditional: {
                        field: 'contactMethod',
                        operator: 'equals',
                        value: 'mail',
                    },
                    validation: z.string().optional(),
                },
            ],
        },
    ],
}
